#ifndef INTERNAL_FRIXIA_H
#define INTERNAL_FRIXIA_H

#include <stdbool.h>
#include <frixia/frixia.h>

bool          INTERNAL_FRIXIA_TIMER_CODE_IS_OK(FTIMER_CODE t);
FRIXIA_RESULT INTERNAL_FRIXIA_TIMER_FD_RESULT(FRIXIA_TIMER_FD_RESULT res);

#endif 