#ifndef INTERNAL_FRIXIA_H
#define INTERNAL_FRIXIA_H

#include <stdbool.h>
#include <frixia/frixia.h>

bool              INTERNAL_FRIXIA_TCP_CODE_IS_OK(FTCP_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_TCP_FD_RESULT(FRIXIA_TCP_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_TCP_CODE_TO_ADD_RESULT(FTCP_CODE code);

bool              INTERNAL_FRIXIA_UDP_CODE_IS_OK(FUDP_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_UDP_FD_RESULT(FRIXIA_UDP_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_UDP_CODE_TO_ADD_RESULT(FUDP_CODE code);

bool              INTERNAL_FRIXIA_FIFO_CODE_IS_OK(FFIFO_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_FIFO_FD_RESULT(FRIXIA_FIFO_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_FIFO_CODE_TO_ADD_RESULT(FFIFO_CODE code);

bool              INTERNAL_FRIXIA_TIMER_CODE_IS_OK(FTIMER_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_TIMER_FD_RESULT(FRIXIA_TIMER_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_TIMER_CODE_TO_ADD_RESULT(FTIMER_CODE code);

bool              INTERNAL_FRIXIA_SIGNAL_CODE_IS_OK(FSIGNAL_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_SIGNAL_FD_RESULT(FRIXIA_SIGNAL_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_SIGNAL_CODE_TO_ADD_RESULT(FSIGNAL_CODE code);

bool              INTERNAL_FRIXIA_INODE_CODE_IS_OK(FINODE_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_INODE_FD_RESULT(FRIXIA_INODE_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_INODE_CODE_TO_ADD_RESULT(FINODE_CODE code);

bool              INTERNAL_FRIXIA_EVENTFD_CODE_IS_OK(FEVENTFD_CODE t);
FRIXIA_RESULT     INTERNAL_FRIXIA_EVENTFD_FD_RESULT(FRIXIA_EVENTFD_FD_RESULT res);
FRIXIA_ADD_RESULT INTERNAL_EVENTFD_CODE_TO_ADD_RESULT(FEVENTFD_CODE code);


#endif 