#ifndef FRIXIA_SUPPORTED_PROTOCOLS
#define FRIXIA_SUPPORTED_PROTOCOLS

typedef enum FRIXIA_SUPPORTED_PROTOCOL
{
    NO_PROTOCOL,
    HTTP,
    FINS,
    HTTPCLIENT,
    FINSCLIENT
    
} FRIXIA_SUPPORTED_PROTOCOL_T;

#endif