#ifndef FRIXIA_CODES_H
#define FRIXIA_CODES_H

#include <limits.h>

enum frixia_code
{
    OK = 0,
    ERR_EPOLL_CREATE = -1,
    ERR_EPOLL_CTL = -2,
    ERR_CHANGE_FILEDESCRIPTOR = -3,
    ERR_MKFIFO = -4,
    ERR_CHANGEFIFO_MKFIFO = -5,
    ERR_CHANGEFIFO_OPENINGFD = -6,
    ERR_EPOLL_WAIT = -7,
    ERR_EPOLL_CTL_ADDTCP = -8,
    ERR_TCP_SOCKET = -9,
    ERR_TCP_SETSOCKETOPT = -10,
    ERR_TCP_BIND= -11,
    ERR_TCP_LISTEN= -12,
    ERR_TCP_STOP= -13,
    ERR_UDP_SOCKET = -14,
    ERR_EPOLL_CTL_ADDUDP = -15,
    ERR_UDP_LISTEN = -16,
    ERR_UDP_NONBLOCKING = -17,
    ERR_UDP_STOP = -18,
    ERR_STOPPING_FRIXIA_TCP = -19,
    ERR_STOPPING_FRIXIA_UDP = -20,
    ERR_ACCEPTING_TCP = -21,
    ERR_READING_TCP = -22,
    ERR_WRITING_TCP = -23,
    ERR_READ_FIFO = -24,
    ERR_STOPPING_FRIXIA_FIFO  = -25,
    ALREADY_LISTENING_ON_TCP_PORT  = -26,
    NO_TCP_ON_SPECIFIED_PORT_FOUND  = -27,
    ERR_READING_FIFO  = -28,
};



#endif
