#ifndef FRIXIA_CODES_H
#define FRIXIA_CODES_H

#include <limits.h>

enum frixia_code
{
    ERR_EPOLL_CREATE = -1,
    ERR_EPOLL_CTL = -2,
    ERR_CHANGE_FILEDESCRIPTOR = -3,
    ERR_MKFIFO = -4,
    ERR_CHANGEFIFO_MKFIFO = -5,
    ERR_CHANGEFIFO_OPENINGFD = -6,
    ERR_EPOLL_WAIT = -7,
    ERR_EPOLL_CTL_ADDUDP = -15,
    ERR_STOPPING_FRIXIA_TCP = -19,
    ERR_STOPPING_FRIXIA_UDP = -20,
    ALREADY_LISTENING_ON_TCP_PORT  = -26,
    NO_TCP_ON_SPECIFIED_PORT_FOUND  = -27,
    ERR_READING_FIFO  = -28,
    ERR_UDP_BIND = -29,
    ERR_FRIXIA_READ = -30
};



#endif
