#ifndef FRIXIA_CODES_H
#define FRIXIA_CODES_H

enum frixia_code
{
    OK,
    ERR_EPOLL_CREATE,
    ERR_EPOLL_CTL,
    ERR_CHANGE_FILEDESCRIPTOR,
    ERR_MKFIFO,
    ERR_CHANGEPIPE_MKFIFO,
    ERR_CHANGEPIPE_OPENINGFD,
    ERR_EPOLL_WAIT,
    ERR_EPOLL_CTL_ADDTCP,
    ERR_TCP_SOCKET,
    ERR_TCP_SETSOCKETOPT,
    ERR_TCP_BIND,
    ERR_TCP_LISTEN,
    ERR_TCP_STOP,
    ERR_UDP_SOCKET,
    ERR_EPOLL_CTL_ADDUDP,
    ERR_UDP_LISTEN,
    ERR_UDP_NONBLOCKING,
    ERR_UDP_STOP,
    ERR_STOPPING_FRIXIA_TCP,
    ERR_STOPPING_FRIXIA_UDP,
    ERR_ACCEPTING_TCP,
    ERR_READING_TCP,
    ERR_WRITING_TCP,
    ERR_READ_PIPE

};



#endif
