#ifndef FEPOLL_CODES_H
#define FEPOLL_CODES_H

typedef enum FRIXIA_EPOLL_CODE
{
    FEPOLL_OK = 0,
    FERR_EPOLL_CREATE = -1,
    FERR_EPOLL_CTL = -2,
    FERR_CHANGE_FILEDESCRIPTOR = -3,
    FERR_MKFIFO = -4,
    FERR_CHANGEFIFO_MKFIFO = -5,
    FERR_CHANGEFIFO_OPENINGFD = -6,
    FERR_EPOLL_WAIT = -7,
    FERR_EPOLL_CTL_ADDUDP = -8,
    FERR_STOPPING_FRIXIA_TCP = -9,
    FERR_STOPPING_FRIXIA_UDP = -10,
    FERR_ALREADY_LISTENING_ON_TCP_PORT  = -11,
    FERR_NO_TCP_ON_SPECIFIED_PORT_FOUND  = -12,
    FERR_READING_FIFO  = -13,
    FERR_UDP_BIND = -14,
    FERR_FRIXIA_EPOLL_CREATION = -15,
    FERR_ADD_STOP_FILEDESCRIPTOR = -16,
    FERR_CREATING_STOP_FILEDESCRIPTOR = -17

} FRIXIA_EPOLL_CODE_T;



#endif